/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export enum ExperienceLevelEnum {
  ENTRY = "entry",
  LEAD = "lead",
  MID = "mid",
  PRINCIPAL = "principal",
  SENIOR = "senior",
  UNKNOWN = "unknown",
}

export enum JobTypeEnum {
  CONTRACT = "contract",
  FULL_TIME = "full-time",
  INTERNSHIP = "internship",
  PART_TIME = "part-time",
  UNKNOWN = "unknown",
}

export enum RemotePolicyEnum {
  HYBRID = "hybrid",
  ON_SITE = "on-site",
  REMOTE = "remote",
  UNKNOWN = "unknown",
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  access_token: string | null;
  expires_at: Int8 | null;
  id: Generated<string>;
  id_token: string | null;
  provider: string;
  providerAccountId: string;
  refresh_token: string | null;
  scope: string | null;
  session_state: string | null;
  token_type: string | null;
  type: string;
  userId: string;
}

export interface JobListing {
  city: string;
  company: string;
  country: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  experience_level: Generated<ExperienceLevelEnum>;
  id: Generated<string>;
  job_type: Generated<JobTypeEnum>;
  note: string | null;
  remote_policy: Generated<RemotePolicyEnum>;
  salary_range: string;
  state: string;
  title: string;
  updated_at: Generated<Timestamp>;
  url: string | null;
  user_id: string;
}

export interface Resume {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Session {
  expires: Timestamp;
  id: Generated<string>;
  sessionToken: string;
  userId: string;
}

export interface User {
  created_at: Generated<Timestamp>;
  email: string;
  emailVerified: Timestamp | null;
  id: Generated<string>;
  image: string | null;
  name: string | null;
  updated_at: Generated<Timestamp>;
}

export interface VerificationToken {
  expires: Timestamp;
  identifier: string;
  token: string;
}

export interface DB {
  Account: Account;
  JobListing: JobListing;
  Resume: Resume;
  Session: Session;
  User: User;
  VerificationToken: VerificationToken;
}
